### ISSUE TITLE
indivSidebar - Request

### ISSUE THREAD

**Issue by redstonerblast** [Papierkorb2292/MultiScoreboard#2]
I know this is a bit to ask for, but can you update the 1.20.4 version to have the indivSidebar feature? I was really wanting to use this feature when I saw it on the mod page, and was disappointed to learn that it is only in the new versions.

**Comment by redstonerblast** [comment]
Also it seems team scoreboards break everything

**Comment by Papierkorb2292** [comment]
> I know this is a bit to ask for, but can you update the 1.20.4 version to have the indivSidebar feature? I was really wanting to use this feature when I saw it on the mod page, and was disappointed to learn that it is only in the new versions.

I'll see when I can do that, I probably don't have enough time until the weekend and I'm not sure how much effort that will be.

**Comment by Papierkorb2292** [comment]
> Also it seems team scoreboards break everything

Are you referring to an incorrect vertical positioning of the sidebar scoreboards when a team scoreboard is displayed? At least that's the only thing that I noticed (in the newest version), it will be fixed in the next release.

**Comment by redstonerblast** [comment]
> Are you referring to an incorrect vertical positioning of the sidebar scoreboards when a team scoreboard is displayed? At least that's the only thing that I noticed (in the newest version), it will be fixed in the next release.

Chat also seems to get moved as well as the hotbar.

**Comment by Papierkorb2292** [comment]
> Chat also seems to get moved as well as the hotbar.

I see, that will also be fixed in the next release, thank you for bringing it to my attention

**Comment by Papierkorb2292** [comment]
The [newest Github release](https://github.com/Papierkorb2292/MultiScoreboard/releases/tag/v1.2.2) now includes a 1.20.4 build
